name: Build

on:
    workflow_dispatch:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@4
            - name: Setup node
              uses: actions/setup-node@4
              with:
                node-version: 20
                cache: npm
            - name: Restore dependencies
              run: npm ci
            - name: Build
              run: npm run build-ci
